# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

proxy_app = "tcp://127.0.0.1:46658"
moniker = "46.101.42.155"
fast_sync = true
db_backend = "memdb"
#log_level = "mempool:error,*:debug"
log_level = "state:info,*:error"

[rpc]
laddr = "tcp://0.0.0.0:46657"

#[mempool]
#recheck = false
#broadcast = false
#wal_dir = ""

[consensus]
#max_block_size_txs = 10000
#create_empty_blocks = false
#timeout_propose = 10000
#skip_timeout_commit = true
#timeout_commit = 1
#wal_light = true
#block_part_size = 262144
create_empty_blocks_interval = 1

[p2p]
#max_msg_packet_payload_size=65536
#send_rate=51200000 # 50 MB/s
#recv_rate=51200000 # 50 MB/s
laddr = "tcp://0.0.0.0:46656"
seeds = "165.227.190.188:46656,165.227.149.101:46656,37.139.30.72:46656"
