version: '3'
services:
  node:
    environment:
      # mnemonic: `release endorse scale across absurd trouble climb unaware actor elite fantasy chair license word rare length business kiss smoke tackle report february bid ginger`
      - RICH_ADDRESS=cosmos1ek9cd8ewgxg9w5xllq9um0uf4aaxaruvcw4v9e
    image: "tendermint/gaia:v0.34.1"
    container_name: node
    volumes:
      - ./nodes:/etc/nodes
      - ./node:/mnt/node
    entrypoint:
      - sh
      - /etc/nodes/first.sh
      - "${MAX_NODES:-2}"
    ports:
      - "26657:26657"
      - "9070:9070"
    restart: "always"