name: App E2E Testing Workflow
on:
  pull_request:
    branches-ignore:
      - "master"
    paths:
      - 'app/**'

env:
  WORKING_DIRECTORY: ./app
  VUE_APP_GRAPHQL_URL: ${{ secrets.LUNIE_API }}
  VUE_APP_FIREBASE_CONFIG: ${{ secrets.VUE_APP_FIREBASE_CONFIG }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      deploy-url: ${{ steps.deploy.outputs.deploy-url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
      - name: NPM Install
        uses: bahmutov/npm-install@v1
      - name: Build App
        run: yarn build
        working-directory: ${{env.WORKING_DIRECTORY}}
      - name: Deploy for E2E Testing 
        uses: nwtgck/actions-netlify@v1.1.4
        id: deploy
        with:
          publish-dir: './app/dist'
          github-token: ${{ secrets.GIT_BOT_TOKEN }}
          deploy-message: "Deployed via GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: false
          overwrites-pull-request-comment: true
          netlify-config-path: ./app/netlify.toml
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
  e2e:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
      - name: NPM Install
        uses: bahmutov/npm-install@v1
      - name: Run Cosmos E2E on Browserstack
        run: |
          yarn test:e2e:browserstack --fe=${{needs.deploy.outputs.deploy-url}} --api=https://production-api.lunie.io
        working-directory: ${{env.WORKING_DIRECTORY}}
        env:
          PASSWORD: ${{secrets.GAIA_PASSWORD}}
          BROWSERSTACK_USERNAME: ${{secrets.BROWSERSTACK_USERNAME}}
          BROWSERSTACK_ACCESS_KEY: ${{secrets.BROWSERSTACK_ACCESS_KEY}}
  e2ePolkadot:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: NPM Install
        uses: bahmutov/npm-install@v1.1.0
      - name: Run Polkadot E2E tests
        run: |
          yarn test:e2e:browserstack --fe=${{needs.deploy.outputs.deploy-url}} --api=https://production-api.lunie.io --network="polkadot-testnet"
        working-directory: ${{env.WORKING_DIRECTORY}}
        env:
          PASSWORD: ${{secrets.GAIA_PASSWORD}}
          BROWSERSTACK_USERNAME: ${{secrets.BROWSERSTACK_USERNAME}}
          BROWSERSTACK_ACCESS_KEY: ${{secrets.BROWSERSTACK_ACCESS_KEY}}
