name: App Release Workflow

on:
  push:
    branches:
      - 'release'
    paths:
      - 'app/**'
env:
  WORKING_DIRECTORY: ./app
jobs:
  createReleasePR:
    name: Create an App Release PR
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
    - name: Configure Lunie Release Bot
      run: git config user.email "bot@lunie.io" && git config user.name "Release Lunie Bot"
      working-directory: ${{env.WORKING_DIRECTORY}}
    - name: Create Release PR
      run: npx simsala release-candidate --semver patch --pending-path ./changes --owner luniehq --repository lunie --token ${{ secrets.GIT_BOT_TOKEN }} --message "Please manually test before merging this to master" --tag-prefix "app"
      working-directory: ${{env.WORKING_DIRECTORY}}
