name: Deploing to DO

on:
  push:
    branches:
      - test
jobs:
  test:
    name: Compile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}
    - name: npm install
      run: npm install
    - name: Build image
      run: docker build -t lunieapi . 
    - name: Save image file
      run: docker save lunieapi | gzip > lunieapi.tgz
    - name: Push to Digital Ocean
      uses: iambeone/pushtodigitalocean@master
      env:
        token:  ${{ secrets.DIGITAL_OCEAN_TOKEN }}
        ports:  4000:4000
        image:  lunieapi
        file:  lunieapi.tgz